=== magento-pangolin/tooling-demo/tests/_support/Generators/testXML.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <xs:element name="config">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="use" type="useType" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="annotations" type="annotationContainerType" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="before" type="metaTestType" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="test" type="testType" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="after" type="metaTestType" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="metaTestType">
        <xs:sequence>
            <xs:element name="dependency" type="dependencyType" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="step" type="stepType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attributeGroup ref="removeAttribute"/>
    </xs:complexType>

    <xs:complexType name="testType">
        <xs:sequence>
            <xs:element name="annotations" type="annotationContainerType" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="dependency" type="dependencyType" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="step" type="stepType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="name" use="required" type="xs:string"/>
        <xs:attributeGroup ref="removeAttribute"/>
    </xs:complexType>

    <xs:complexType name="stepType">
        <xs:attribute name="actor" type="xs:string" use="required"></xs:attribute>
        <xs:attribute name="function" type="xs:string" use="required"></xs:attribute>
        <xs:attribute name="selector" type="xs:string" use="optional"></xs:attribute>
        <xs:attribute name="parameter" type="xs:string" use="optional"></xs:attribute>
        <xs:attribute name="data" type="xs:string" use="optional"></xs:attribute>
        <xs:attribute name="field" type="xs:string" use="optional"></xs:attribute>
        <xs:attribute name="variable" type="xs:string" use="optional"></xs:attribute>
        <xs:attribute name="name" type="xs:string" use="required"></xs:attribute>
        <xs:attributeGroup ref="removeAttribute"/>
    </xs:complexType>

    <xs:complexType name="useType">
        <xs:attribute name="path" type="xs:string" use="required"/>
        <xs:attributeGroup ref="removeAttribute"/>
    </xs:complexType>

    <xs:complexType name="dependencyType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="type" use="required"/>
                <xs:attributeGroup ref="removeAttribute"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="annotationContainerType">
        <xs:sequence>
            <xs:element type="annotationType" name="features" minOccurs="0" maxOccurs="unbounded"></xs:element>
            <xs:element type="annotationType" name="stories" minOccurs="0" maxOccurs="unbounded"></xs:element>
            <xs:element type="annotationType" name="title" minOccurs="0" maxOccurs="unbounded"></xs:element>
            <xs:element type="annotationType" name="description" minOccurs="0" maxOccurs="unbounded"></xs:element>
            <xs:element type="annotationType" name="severity" minOccurs="0" maxOccurs="unbounded"></xs:element>
            <xs:element type="annotationType" name="testCaseId" minOccurs="0" maxOccurs="unbounded"></xs:element>
            <xs:element type="annotationType" name="group" minOccurs="0" maxOccurs="unbounded"></xs:element>
            <xs:element type="annotationType" name="env" minOccurs="0" maxOccurs="unbounded"></xs:element>
            <xs:element type="annotationType" name="return" minOccurs="0" maxOccurs="unbounded"></xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="annotationType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attributeGroup ref="removeAttribute"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:attributeGroup name="removeAttribute">
        <xs:attribute type="xs:boolean" name="remove" use="optional" default="false">
            <xs:annotation>
                <xs:documentation>
                    Set to true to remove this element during parsing.
                </xs:documentation>
            </xs:annotation>
        </xs:attribute>
    </xs:attributeGroup>
</xs:schema>

=== magento-pangolin/tooling-demo/tests/acceptance/AdminLogin/LoginOnAdminLoginPageCest.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Test XML Example -->
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../_support/Generators/testXML.xsd">
    <annotations>
        <features>Admin Login</features>
        <stories>Logging In using raw Codeception commands.</stories>
        <stories>Logging In using Codeception PageObject methods.</stories>
        <group>banana</group>
        <env>chrome</env>
        <env>firefox</env>
        <env>phantomjs</env>
    </annotations>

    <before>
        <dependency type="AdminNavigation">I</dependency>

        <step actor="I" function="goToTheAdminLoginPage" name="goToTheAdminLoginPage"/>
    </before>

    <test name="shouldBeAbleToLoginUsingCodeceptionCommands">
        <annotations>
            <title>You should be able to Login to the Admin</title>
            <description>You should land on the Admin Dashboard after Logging In</description>
            <severity>CRITICAL</severity>
            <testCaseId>#</testCaseId>
            <return>void</return>
        </annotations>

        <dependency type="AcceptanceTester">I</dependency>

        <step name="enterTheUsername" actor="I" function="fillField" selector="#username" parameter="admin"/>
        <step name="enterThePassword" actor="I" function="fillField" selector="#login" parameter="123123q"/>
        <step name="clickOnSignIn"    actor="I" function="click"     selector=".actions .action-primary"/>
        <step name="waitForPageLoad"  actor="I" function="waitForPageLoad"/>
    </test>

    <test name="shouldBeAbleToLoginUsingPageObjects">
        <annotations>
            <title>You should be able to Login to the Admin</title>
            <description>You should land on the Admin Dashboard after Logging In.</description>
            <severity>CRITICAL</severity>
            <testCaseId>#</testCaseId>
            <return>void</return>
        </annotations>

        <dependency type="AdminLoginPage">I</dependency>

        <step name="enterUsernameField" actor="I" function="enterUsernameField" parameter="'admin'"/>
        <step name="enterPasswordField" actor="I" function="enterPasswordField" parameter="'123123q'"/>
        <step name="clickSignInButton"  actor="I" function="clickSignInButton"/>
    </test>

    <after>
        <dependency type="AdminNavigation">I</dependency>

        <step actor="I" function="shouldBeOnTheAdminDashboardPage" name="shouldBeOnTheAdminDashboardPage"/>
    </after>
</config>

=== magento-pangolin/tooling-demo/tests/acceptance/Examples/TemplateCestFile.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Test XML Example -->
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../_support/Generators/testXML.xsd">
    <use path="AcceptanceTester"/>

    <annotations>
        <features></features>
        <stories></stories>
        <group></group>
        <env></env>
    </annotations>

    <before>
        <dependency type=""></dependency>

        <step actor="" function="" name=""/>
    </before>

    <test name="">
        <annotations>
            <title></title>
            <description></description>
            <severity></severity>
            <testCaseId></testCaseId>
            <return>void</return>
        </annotations>

        <dependency type=""></dependency>

        <step actor="" function="" parameter="" name=""/>
        <step actor="" function="" selector="" parameter="" name=""/>
    </test>

    <after>
        <dependency type=""></dependency>

        <step actor="" function="" name=""/>
    </after>
</config>

=== magento-pangolin/tooling-demo/tests/acceptance/Sales/CreateOrderViaAdminCest.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Test XML Example -->
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../_support/Generators/testXML.xsd">
    <annotations>
        <features>Features</features>
        <stories>Create an Order via the Admin</stories>
        <group>skip</group>
        <group>add</group>
        <group>sales</group>
        <group>orders</group>
        <env>chrome</env>
        <env>firefox</env>
        <env>phantomjs</env>
    </annotations>

    <before>
        <dependency type="AdminStep">I</dependency>
        <step actor="I" function="loginAsAdmin" name="loginAsAdmin"/>
    </before>

    <test name="createOrderViaAdmin">
        <annotations>
            <title>Create an Order via the Admin</title>
            <description>Setup a Category, Product, Customer and place an Order using them via the Admin.</description>
            <severity>CRITICAL</severity>
            <testCaseId>#</testCaseId>
            <return>void</return>
        </annotations>

        <dependency type="AdminStep">I</dependency>
        <dependency type="AdminCustomerPage">adminCustomerPage</dependency>
        <dependency type="AdminCategoryPage">adminCategoryPage</dependency>
        <dependency type="AdminProductPage">adminProductPage</dependency>
        <dependency type="AdminOrderGrid">adminOrderGrid</dependency>
        <dependency type="AdminOrderAddPage">adminOrderAddPage</dependency>
        <dependency type="AdminOrderDetailsPage">adminOrderDetailsPage</dependency>

        <step actor="I" function="getCustomerData" variable="customerDetails" name="getCustomerData"/>
        <step actor="I" function="getCustomerData" variable="categoryDetails" name="getCategoryData"/>
        <step actor="I" function="getCustomerData" variable="productDetails" name="getProductData"/>

        <!--<step actor="" function="" selector="" parameter="" name=""/>-->

        <step actor="I" function="goToTheAdminAllCustomersGrid" name="goToTheAdminAllCustomersGrid"/>
        <step actor="adminCustomerPage" function="addBasicCustomerWithAddress" variable="$customerDetails" name="addBasicCustomerWithAddress"/>

        <step actor="I" function="goToTheAdminCategoriesPage" name="goToTheAdminCategoriesPage"/>
        <step actor="adminCategoryPage" function="addBasicCategory" variable="$categoryDetails" name="addBasicCategory"/>

        <step actor="I" function="goToTheAdminCatalogPage" name="goToTheAdminCatalogPage"/>
        <step actor="adminProductPage" function="addBasicProductUnderCategory" parameter="$productDetails, $categoryDetails" name="addBasicProductUnderCategory"/>

        <step actor="I" function="goToTheAdminOrdersGrid" name="goToTheAdminOrdersGrid"/>
        <step actor="adminOrderGrid" function="clickOnCreateNewOrderButton" name="clickOnCreateNewOrderButton"/>

        <step actor="adminOrderAddPage" function="enterCustomerEmailSearchTerm" parameter="$customerDetails['email']" name="enterCustomerEmailSearchTerm"/>
        <step actor="adminOrderAddPage" function="clickOnCustomerSearchButton" name="clickOnCustomerSearchButton"/>
        <step actor="adminOrderAddPage" function="clickOnCustomerFor" parameter="$customerDetails['email']" name="clickOnCustomerFor"/>

        <step actor="adminOrderAddPage" function="clickOnDefaultStoreView" name="clickOnDefaultStoreView"/>

        <step actor="adminOrderAddPage" function="clickOnAddProductsButton" name="clickOnAddProductsButton"/>
        <step actor="adminOrderAddPage" function="enterProductSkuSearchField" parameter="$productDetails['sku']" name="enterProductSkuSearchField"/>
        <step actor="adminOrderAddPage" function="clickOnProductsSearchButton" name="clickOnProductsSearchButton"/>
        <step actor="adminOrderAddPage" function="clickOnProductSkuFor" parameter="$productDetails['sku']" name="clickOnProductSkuFor"/>
        <step actor="adminOrderAddPage" function="clickOnAddSelectedProductsToOrderButton" name="clickOnAddSelectedProductsToOrderButton"/>

        <step actor="adminOrderAddPage" function="clickOnGetShippingMethodsAndRatesLink" name="clickOnGetShippingMethodsAndRatesLink"/>
        <step actor="adminOrderAddPage" function="clickOnFixedShippingMethod" name="clickOnFixedShippingMethod"/>

        <step actor="adminOrderAddPage" function="clickOnBottomSubmitButton" name="clickOnBottomSubmitButton"/>

        <step actor="adminOrderDetailsPage" function="verifyThatYouCreatedAnOrderMessageIsPresent" name="verifyThatYouCreatedAnOrderMessageIsPresent"/>
        <step actor="adminOrderDetailsPage" function="verifyThereIsAnOrderNumber" name="verifyThereIsAnOrderNumber"/>
        <step actor="adminOrderDetailsPage" function="verifyThatTheOrderWasPlacedToday" name="verifyThatTheOrderWasPlacedToday"/>
        <step actor="adminOrderDetailsPage" function="verifyOrderStatusPending" name="verifyOrderStatusPending"/>
        <step actor="adminOrderDetailsPage" function="verifyPurchasedFromDefaultStoreView" name="verifyPurchasedFromDefaultStoreView"/>

        <!--<step actor="adminOrderDetailsPage" function="verifyCustomerName"  parameter="$customerName" name="verifyCustomerName"/>-->
        <step actor="adminOrderDetailsPage" function="verifyCustomerEmail" parameter="$customerDetails['email']" name="verifyCustomerEmail"/>
        <step actor="adminOrderDetailsPage" function="verifyCustomerGroup" parameter="'General'" name="verifyCustomerGroup"/>

        <step actor="adminOrderDetailsPage" function="verifyBillingAddressInformation"  parameter="$customerDetails" name="verifyBillingAddressInformation"/>
        <step actor="adminOrderDetailsPage" function="verifyShippingAddressInformation" parameter="$customerDetails" name="verifyShippingAddressInformation"/>

        <step actor="adminOrderDetailsPage" function="verifyPaymentTypeCheckMoneyOrder" name="verifyPaymentTypeCheckMoneyOrder"/>
        <step actor="adminOrderDetailsPage" function="verifyPaymentCurrencyUSD" name="verifyPaymentCurrencyUSD"/>

        <step actor="adminOrderDetailsPage" function="verifyShippingMethodFixedRate" name="verifyShippingMethodFixedRate"/>
        <step actor="adminOrderDetailsPage" function="verifyShippingHandlingPrice"   parameter="'$0.00'" name="verifyShippingHandlingPrice"/>

        <step actor="adminOrderDetailsPage" function="verifyItemsOrderedFor" parameter="$productDetails" name="verifyItemsOrderedFor"/>

        <step actor="adminOrderDetailsPage" function="verifyOrderStatusDropDownPending" name="verifyOrderStatusDropDownPending"/>
        <step actor="adminOrderDetailsPage" function="verifyOrderComments" parameter="''" name="verifyOrderComments"/>

        <step actor="adminOrderDetailsPage" function="verifySubTotalPrice"         parameter="$productDetails['price']" name="verifySubTotalPrice"/>
        <step actor="adminOrderDetailsPage" function="verifyShippingHandlingPrice" parameter="'$0.00'" name="verifyShippingHandlingPrice"/>
    </test>
</config>

=== magento-pangolin/tooling-demo/tests/acceptance/Examples/MinimumTestCest.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Test XML Example -->
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../_support/Generators/testXML.xsd">
    <annotations>
        <env>chrome</env>
        <group>example</group>
    </annotations>

    <test name="MinimumFieldsTest">
        <annotations>
            <return>void</return>
        </annotations>

        <dependency type="AcceptanceTester">I</dependency>

        <step actor="I" function="amOnUrl"         parameter="'http://127.0.0.1:32770/admin/'" name="amOnPage"/>
        <step actor="I" function="fillField"       selector="#username" parameter="admin"      name="fillField"/>
        <step actor="I" function="fillField"       selector="#login"    parameter="123123q"    name="fillField"/>
        <step actor="I" function="click"           selector=".actions .action-primary"         name="clickOnSignIn"/>
        <step actor="I" function="waitForPageLoad" name="waitForPageLoad"/>
    </test>
</config>
